### ISSUE TITLE
UI update to do ( August 1st ) 

### ISSUE THREAD

**Issue by bowon** [bowon/demo_july10#13]
- Until August 6
- [ ] Adding CSS control at interaction.js  ( CSS Browser compatibility control )
- [x] Make the Reset layer/ about the data button alignment fixed at one line 
- [x] Icons for industry history 
- [x] Population density map needs new color palette. Orange based scheme is candidate. 

- After August 6 to go
- [ ] Responsive setting on the navbar  

~~Browser resolution should reflected at basemap zoomStart/zoomBoundaries control.~~

**Comment by clhenrick** [comment]
@bowon any responsive UI designs should probably be done last. Also make sure to implement them with CSS media queries instead of Javascript when possible.

**Comment by clhenrick** [comment]
moving to #8
