### ISSUE TITLE
UI bugs

### ISSUE THREAD

**Issue by clhenrick** [bowon/demo_july10#18]
- [x] Legend for demographic data layers should be removed, probably need to rework logic in the hideShow() function: https://github.com/bowon/demo_july10/blob/master/js/main.js#L192-L227

- [x] Data layer buttons should be active only when clicked and then be de-active when clicked again & data layer is hidden.

**Comment by bowon** [comment]
For data layer button reaction, I would get your feedback for current(August 11th) result because it seems corrected after removing Bootstrap.

**Comment by clhenrick** [comment]
@bowon yes we fixed this on friday so I'm closing the issue.
