### ISSUE TITLE
Legends interaction error with Reset Layer button

### ISSUE THREAD

**Issue by bowon** [bowon/demo_july10#22]
- [x] Removing all template based legends after reset layer pressed
- [ ] After pressing Reset layer button, same type of legend are renderable.

**Comment by clhenrick** [comment]
Ah I forgot about that part. Should be an easy fix though. Want to try to
add it or should I?

On Monday, August 10, 2015, bowon <notifications@github.com> wrote:

>
>    - Removing all template based legends after reset layer pressed
>    - After pressing Reset layer button, same type of legend are
>    renderable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bowon/demo_july10/issues/22>.
>


-- 

-Chris L Henrick
-------------------------
MFA, Design & Technology
Parsons, The New School For Design

https://clhenrick.github.io
*Github:* @clhenrick <https://github.com/clhenrick> *Twitter:*
@chrislhenrick <https://twitter.com/chrislhenrick>

“Whenever I see an adult on a bicycle, I no longer despair for the future
of the human race.”
— H.G. Wells

**Comment by clhenrick** [comment]
- @bowon for the second to-do are you saying that if the user clicks the button a second time that all of the data layers and legends that were previously displayed would reappear? If so I don't think that makes sense. A "reset" or "clear" button should only set the map to it's initial state and not serve as a hide/show toggle.
