### ISSUE TITLE
Infowindow bugs [high priority]

### ISSUE THREAD

**Issue by clhenrick** [bowon/demo_july10#38]
- [x] styling of infowindows should scroll
- [x] check that desired attribute data is populating infowindow
- [x] add vertical scroll bar to infowindows
- [x] sometimes infowindows won't open again after closing them.

**Comment by clhenrick** [comment]
Fix problem with Infowindow not displaying in correct location:
![screen shot 2015-09-05 at 8 35 55 pm](https://cloud.githubusercontent.com/assets/161748/9701841/c3456c56-540d-11e5-8e2d-c7ec204e1a40.png)

**Comment by clhenrick** [comment]
Fix text overflow
![screen shot 2015-09-05 at 8 38 19 pm](https://cloud.githubusercontent.com/assets/161748/9701849/12ae2bfc-540e-11e5-9fe5-63a10ff07fac.png)

**Comment by bowon** [comment]
@clhenrick Regarding to the size of Info window, I'm leaving a note here. 
Infowindow should show maximum five lines of information with scroll that already prioritized :facility_or_owner ,description, type of pollution, address ,date. The order at the interactivity section belongs to this.

**Comment by clhenrick** [comment]
still need to resolve issue when info window opens at a different location than where the user clicks...

**Comment by bowon** [comment]
"Reset layer" button does not remove opened info windows.  I feel it could be OK if user would keep the info window as a memo. How do you feel about this issue?

**Comment by clhenrick** [comment]
Good catch. Also the info windows are still buggy in that they aren't
opening in the correct place on the map, at least that's what I'm
experiencing. Are you?
Like they open just below where you click instead of on the position of
your mouse.

There's probably a method to close the infowindows that can get called when
reset layers is clicked. I will look into it.

On Saturday, September 19, 2015, Bowon Chung <notifications@github.com>
wrote:

> "Reset layer" button does not remove opened info windows. I feel it could
> be OK if user would keep the info window as a memo. How do you feel about
> this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bowon/demo_july10/issues/38#issuecomment-141622948>.
>


-- 

-Chris L Henrick
-------------------------
MFA, Design & Technology
Parsons, The New School For Design

http://chrishenrick.com
*Github:* @clhenrick <https://github.com/clhenrick> *Twitter:*
@chrislhenrick <https://twitter.com/chrislhenrick>

“Whenever I see an adult on a bicycle, I no longer despair for the future
of the human race.”
— H.G. Wells

**Comment by bowon** [comment]
@clhenrick  
I agree about the position issue. How about removing the outline of infowindow? 
I feel like the position of infowindow arrow itself (white part) is correct... maybe 1px wrong. Since the outline of the info window is quite thick(which is probably gray opacity 30% line 4px), the outline pushs the arrow of info window at 4px lower position than you actually picked. Because of the bumping motion at tooltip, 4px look more than 4px.

 div.cartodb-popup div.cartodb-popup-content-wrapper {
    width:190px;
    max-width: 190px;
    padding:12px 19px 12px 19px;
    overflow-x: hidden;
    background:url('../img/light.png') repeat-y -452px 0;
  }
 div.cartodb-popup div.cartodb-popup-tip-container {
    width:226px;
    height:20px;
    background:url('../img/light.png') no-repeat 0 0;
  }

It seems like the img/light.png and padding shapes the outline. I tried to overlap those with new style but wasn't successful.

**Comment by clhenrick** [comment]
@bowon something in the CSS is overriding the CartoDB CSS styles for the infowindows. Going to look into it today. 

Ideally we don't / shouldn't need to modify the CSS for the infowindows at all. If you look at `test.html` file I just added to the repo you can see that the info-windows display correctly without the custom CSS files we've created. This leads me to believe that the custom CSS is causing the info-window issues.

**Comment by clhenrick** [comment]
@bowon this issue is dependent on resolving #43 first, so please make that a priority.

**Comment by bowon** [comment]
@clhenrick  I checked firefox and found what you are saying: The problem wasn't appear at Chrome/Safari for me.

**Comment by clhenrick** [comment]
some info-windows don't open again after closing them.
![screen shot 2015-09-21 at 3 45 57 pm](https://cloud.githubusercontent.com/assets/161748/10002953/fe5152d0-6077-11e5-9e58-6157a67f76f6.png)

**Comment by bowon** [comment]
This is ![the info window position at firefox](https://cloud.githubusercontent.com/assets/2758146/10007254/b62d5246-6091-11e5-939d-29adc74f7c4d.jpg) Am I following you correctly?

**Comment by clhenrick** [comment]
yes


-Chris L Henrick
-------------------------
MFA, Design & Technology
Parsons, The New School For Design

http://chrishenrick.com
*Github:* @clhenrick <https://github.com/clhenrick> *Twitter:*
@chrislhenrick <https://twitter.com/chrislhenrick>

“Whenever I see an adult on a bicycle, I no longer despair for the future
of the human race.”
— H.G. Wells

**Comment by clhenrick** [comment]
@bowon That's not what I'm seeing in Firefox though. Are you sure you're looking at it with the latest version at the master branch?

**Comment by bowon** [comment]
Ok it was gone after I upgrade the Firefox to recent version.
The tested version is our latest version that updated today.

**Comment by bowon** [comment]
@clhenrick  I'll check the mouse position / coordinate match issue later later on.
