### ISSUE TITLE
adjust size of point-data markers based on zoom level

### ISSUE THREAD

**Issue by clhenrick** [bowon/demo_july10#40]
@bowon could you modify the CartoCSS for the point data layers (polluted points, waste transfer stations) so that the marker increases in size as the zoom level is higher? Let me know if you have questions about this.

**Comment by bowon** [comment]
Got it! If it is same to Mapbox studio, I know how to do it.

Bowon

**Comment by clhenrick** [comment]
Great, @bowon after changing the CartoCSS in the corresponding `.mss` files be sure to run `node carto-to-text.js`. You can install Node JS on your computer here if you haven't already: https://nodejs.org/en/

**Comment by bowon** [comment]
I have node.js in my machine. Thanks. will do it right now.

**Comment by bowon** [comment]
This issue is closed.
