### ISSUE TITLE
CartoDB data changes

### ISSUE THREAD

**Issue by clhenrick** [bowon/demo_july10#41]
- [x] format median income values to money data type.
- [x] comma separate longer numeric values (acs, asthma)
- [x] change values for percentages to be formatted as % with only 2 significant digits
- [x] change names of fields to be more human readable when necessary
- [x] any links should be wrapped inside an `<a target="_blank" href="http://...">link text</a>` so they are hyper linked (eg: the sources column in industrial_points)

**Comment by clhenrick** [comment]
@bowon please create a list of all tables with their corresponding columns that need their names changed when displayed to the user in an infowindow. For example the table `industrialhistory` has  the column `gid` which would make more sense to be displayed as `tour stop` to the user.

**Comment by bowon** [comment]
@clhenrick Please check this [link](https://gist.github.com/25ca28482ea035f10693.git). I can put the list if you tell me where to place it. I will double-check the interactivity part as well. gid and nag-id removed.

**Comment by clhenrick** [comment]
@bowon did any of the names for the data layers change? Industrial History points and lines don't seem to be working...

**Comment by clhenrick** [comment]
@bowon to resolve this issue I will need access to the Nag cartodb account. Please email me the credentials.

**Comment by bowon** [comment]
the table name was different. 

industrialhistory_points industrialhistory_lines

I just changed as above.

Bowon

**Comment by bowon** [comment]
Table acs_5yr_2013_merge has values of formatted two digits % at the column with other data.

**Comment by clhenrick** [comment]
@bowon what is specific name of column that has the data formatted correctly?

**Comment by bowon** [comment]
The %Column name is same to original table.

**Comment by clhenrick** [comment]
I'm not following you / understanding...

**Comment by bowon** [comment]
Please just replace the current table to the new table.

**Comment by clhenrick** [comment]
So the table was updated and the name changed? what is the name of the new
table?


-Chris L Henrick
-------------------------
MFA, Design & Technology
Parsons, The New School For Design

http://chrishenrick.com
*Github:* @clhenrick <https://github.com/clhenrick> *Twitter:*
@chrislhenrick <https://twitter.com/chrislhenrick>

“Whenever I see an adult on a bicycle, I no longer despair for the future
of the human race.”
— H.G. Wells

**Comment by bowon** [comment]
The table “ acs_5yr_2013_merge " is for the data manipulation.  
Because $ and number formatting wasn’t done yet, I didn’t replaced this table to original one. 

Bowon

**Comment by clhenrick** [comment]
So acs_5yr_2013_merge is a table with new data that needs to be
implemented, correct?


-Chris L Henrick
-------------------------
MFA, Design & Technology
Parsons, The New School For Design

http://chrishenrick.com
*Github:* @clhenrick <https://github.com/clhenrick> *Twitter:*
@chrislhenrick <https://twitter.com/chrislhenrick>

“Whenever I see an adult on a bicycle, I no longer despair for the future
of the human race.”
— H.G. Wells

**Comment by bowon** [comment]
Following 4 columns were updated. 

percent_hispanic, 
percent_nonhispanic_white, 
percent_nonhispanic_black,
 percent_nonhispanic_asian  

at acs_5yr_2013_merge. 

median_household_income column wasn’t updated yet. 

Bowon

**Comment by clhenrick** [comment]
To Do: remove all columns we don't need as right now we are bringing all of these columns into the dataset when we don't need to. Probably best to create a new table by selecting the columns we want to keep.

**Comment by bowon** [comment]
I include my sql at the file except copy and merge part because those were done at Cartodb editor.
I copied four demographics columns as acs_5yr_2013_copy and rounded the number and merged it at original table : result is acs_5yr_2013_merge.  If you feel these are redundant, you can remove it.

**Comment by bowon** [comment]
@clhenrick Could you tell me why the sql of rounding part was removed? Would you like to leave it just for formatting? The rounding up to the one for two last digit should remain because it is pretty huge number in population data.

**Comment by clhenrick** [comment]
@bowon I didn't see it. Copy and paste it here.

**Comment by bowon** [comment]
@clhenrick 
SELECT percent_hispanic,percent_nonhispanic_asian, percent_nonhispanic_black,percent_nonhispanic_white FROM acs_5yr_2013;
COPY 
ALTER TABLE acs_5yr_2013_copy ADD COLUMN per_hispanic numeric;
ALTER TABLE acs_5yr_2013_copy ADD COLUMN per_nonhis_asian numeric;
ALTER TABLE acs_5yr_2013_copy ADD COLUMN per_nonhis_black numeric;
ALTER TABLE acs_5yr_2013_copy ADD COLUMN per_nonhis_white numeric;
UPDATE acs_5yr_2013_copy SET per_hispanic = round(percent_hispanic::numeric,2);
UPDATE acs_5yr_2013_copy SET per_nonhis_asian = round(percent_nonhispanic_asian::numeric,2);
UPDATE acs_5yr_2013_copy SET per_nonhis_black = round(percent_nonhispanic_black::numeric,2);
UPDATE acs_5yr_2013_copy SET per_nonhis_white = round(percent_nonhispanic_white::numeric,2);
ALTER TABLE acs_5yr_2013_copy DROP COLUMN percent_hispanic CASCADE;
ALTER TABLE acs_5yr_2013_copy DROP COLUMN percent_nonhispanic_asian CASCADE;
ALTER TABLE acs_5yr_2013_copy DROP COLUMN percent_nonhispanic_black CASCADE;
ALTER TABLE acs_5yr_2013_copy DROP COLUMN percent_nonhispanic_white CASCADE;
ALTER TABLE acs_5yr_2013_copy per_hispanic RENAME TO percent_hispanic;
ALTER TABLE acs_5yr_2013_copy RENAME COLUMN per_nonhis_asian TO percent_nonhispanic_asian;
ALTER TABLE acs_5yr_2013_copy RENAME COLUMN per_nonhis_black TO percent_nonhispanic_black;
ALTER TABLE acs_5yr_2013_copy RENAME COLUMN per_nonhis_white TO percent_nonhispanic_white;

It seems like I wrote wrong in last four lines at last commit. I fixed renaming part.

**Comment by clhenrick** [comment]
Okay, and you didn't include the SQL code for the rounded median income or rounded population density, correct?

**Comment by clhenrick** [comment]
I'm going to re-write all this code so it's more efficient over all.

**Comment by bowon** [comment]
I have sql record for those two calculation that I’ve run including query for making line for industrial history. Do you need all of these?

Update acs_5yr_2013 Set calc_pop = ( mhhi / totpop ) *1000
Update acs_5yr_2013 Set roundedcpop = round(Calc_pop)

Update asthma Set asthma5ypop = ( Asthma5y / totpop ) *1000
Update asthma Set rounyed_asthma5ypop = round(asthma5ypop)


for making industrial historical tour line
SELECT ST_MakeLine(the_geom order by id ASC) as the_geom_webmercator  FROM industrialhistory

I need to check out the column name one more time please give me time for it. 
I didn’t save the last two digit because it was not %.  result of round(asthma5ypop) was very weird since it doesn’t actually rounding up at that half as expected ( expectation : 40.7% => 41%   |  result : 40.7% -> 40% ) So manually fixed this problem at the moment by checking all the result. It is embarrassing to discuss openly but I should be honest for this calculation. 

Bowon

**Comment by clhenrick** [comment]
@bowon don't worry about it I'll clean up the code later. We want to make the data import and formatting repeatable for future updates which is why it's important to have SQL for all the steps taken to format the data.

If you have any other SQL to add please post it to #52

**Comment by bowon** [comment]
OK. I check my record after today’s class. 

Bowon
