### ISSUE TITLE
Create list of data-table infowindow column names exactly as they appear in the data table

### ISSUE THREAD

**Issue by clhenrick** [bowon/demo_july10#44]
@bowon I need for you to update the list you gave me of the fields to be displayed for each data layer's infowindow. I need to know what the **exact column name** is for the corresponding infowindow label.

For example for the Polluted Points layer:

| Infowindow Name       | Actual Column Name |
|-----------------------|--------------------|
| Facility or Owner     |                    |
| Description           |                    |
| Type of Pollution     |                    |
| Address               |                    |
| Date                  |                    |
| Agency Program        |                    |
| More Information      |                    |
| Quantity of Pollution |                    |
| Remediated Status     |                    |
| Responding Agency     |                    |
| Source                |                    |

Next to "Facility or Owner" would be `facility_or_owner`

**Comment by clhenrick** [comment]
will resolve this when I have access to the CartoDB account.

**Comment by bowon** [comment]
Please check the gist link that I sent you at hangout. 
I updated the file roughly. If it doesn’t work for you, please let me know. 

Bowon
