### ISSUE TITLE
Coherency needed at the order of legend title 

### ISSUE THREAD

**Issue by bowon** [bowon/demo_july10#46]
- [ ] ~~Include title at Waste Transfer Station~~
- [x] Remove title "polluted places"  
- [x] "plume" should be "polluted and remediated sites"

~~Waste Transfer Station~~
~~[ icon ] Waste Transfer Station~~

**Comment by clhenrick** [comment]
@bowon Adding a title to Waste Transfer Stations seems redundant to me.

**Comment by bowon** [comment]
@clhenrick Otherwise, wts will randomly placed under other categories, because of the subtitles. Do you have any suggestion?

**Comment by clhenrick** [comment]
Perhaps we can add a ruled line between the legends to distinguish them.

**Comment by clhenrick** [comment]
ie:
Legend Title:

- a
- b
- c

---------

- x

--------

Legend Title 2

- a 
- b
- c

**Comment by bowon** [comment]
@clhenrick While I was working on this project, <HR noshade color = 'subtle_gray'> was asked me to remove whenever I used it.

**Comment by clhenrick** [comment]
Well I think it's fine the way it is, let's leave it that way unless they complain.

**Comment by bowon** [comment]
Gorgeous. Thanks for your lovely feedback.
