### ISSUE TITLE
backup mapbox basemap tiles [high priority]

### ISSUE THREAD

**Issue by clhenrick** [bowon/demo_july10#53]
@bowon can you please email me the following: 

- the `tm2` directory for the Mapbox Studio project you created for the basemap 
- any GIS data that was overlaid on top (think it's just truck routes and zipcodes, correct?)

Please send these to me asap, it's important that we have a backup of them. Thanks!

**Comment by bowon** [comment]
@clhenrick 1.Shapefile of Congressional district 2013 2.Truck route 3.Shapefiles of Zipcodes. The original files were kept at google drive. Will upload those here later today.

**Comment by bowon** [comment]
@clhenrick Related to the mapbox studio project file, the mss files for truck route and polygon shapfiles will be updated here. For the other part, I've been producing instruction for design guideline deliverables including basemap design: user flow, design concept, information architecture, design format of UI, base map selected shapefiles, columns, selected data, palette, zoom level design etc. I once show you a part of it before for discussing interface design. Instruction for the updating Cartodb data and base map design guideline was part of deliverables for the client.

**Comment by clhenrick** [comment]
@bowon please send me the files to me, don't upload them here. Thanks.

**Comment by bowon** [comment]
I checked the Cartodb account and found the original files for basemap at there and updated some shapefiles that wasn’t placed. For the Mapbox project, I saved files at iCloud, Google drive, personal hard drive and Mapbox account.  Please tell me why this is urgent.

**Comment by clhenrick** [comment]
@bowon we need them on a separate MapBox account for Nag, not keep them
on a personal one. Again please send them so I can do this, I have
connections with people at MapBox so can get an account with more space for
free for a non-profit.

On Tuesday, September 22, 2015, Bowon Chung <notifications@github.com>
wrote:

> I checked the Cartodb account and found the original files for basemap at
> there and updated some shapefiles that wasn’t placed. For the Mapbox
> project, I saved files at iCloud, Google drive, personal hard drive and
> Mapbox account. Please tell me why this is urgent.
>
>
> > On Sep 22, 2015, at 4:16 PM, Chris Henrick <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > @bowon please send me the files to me, don't upload them here. Thanks.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bowon/demo_july10/issues/53#issuecomment-142463986>.
>


-- 

-Chris L Henrick
-------------------------
MFA, Design & Technology
Parsons, The New School For Design

http://chrishenrick.com
*Github:* @clhenrick <https://github.com/clhenrick> *Twitter:*
@chrislhenrick <https://twitter.com/chrislhenrick>

“Whenever I see an adult on a bicycle, I no longer despair for the future
of the human race.”
— H.G. Wells

**Comment by clhenrick** [comment]
@bowon reason it's high priority is that when we deliver the site to Nag we want the tiles to be connected to a Mapbox account set up for them. I want to make sure that's working in advance. 

If you'd like to add the `tm2` files to this repo feel free to but it would helpful for you to send me a copy of them as well. Thanks.

**Comment by bowon** [comment]
First of all, Thank you very mush for your help and my apology for my attitude. I recognize that we passed our dead line. But I’m a full-time student in semester and have to turn in my assignment in time and need to work one by one. 

I already made NAG Mapbox account that has same setting for the CartoDB account. Since our development process is not done yet, I didn’t used it. Please check your Hangout.  I'll send you links to share the basemap backup at google drive. 

Bowon
